name: testing actions

on:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"
          architecture: "x64"

      - name: setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.1.1

      - name: Print Java home
        run: |
          echo $JAVA_HOME
          ls -l $JAVA_HOME/bin/java
          java --version
          echo "separador"
          mvn -v

      - name: build dummy
        run: |
          cd my-app
          mvn package
